### PR TITLE
Added support to modify the parameter bounds after  GP object creation

### PR DESCRIPTION
**Pull request by Kamuish**
Hello,

If possible could you write a quick tutorial on how to run/test the code base? 
I have tested the function on an archaic way and it appears to be running, but I couldn't write unit tests for it

### CODE REVIEW

**Comment by Kamuish** [comment]
@dfm This should be working as expected but the list with the parameter bounds is not being changed. Do you have any idea why? It doesn't give an error, but the list is not being updated, even on the same scope (you can see with the print statements).

Do you have to define the parameter_bounds.setter to be able to change it? But that is not needed if you only want to change elements inside a list which is returned by a @property decorator.

Could you give me some insight into the sittuation?

**Comment by dfm** [comment]
I should write developer docs, I agree, but I'm up to my eyeballs for at least the next few weeks so it'll take me a while to get there. Please feel free to ping me again if you don't hear back in the next month or two. Thanks for your patience!

**Comment by Kamuish** [comment]
No problem. I think that I have already figured how to test the code and how to fix the previously mentioned bug.  I will try to change the pull request so that it works.  I will also start to contributing some more documentation of the module, if it's ok by you.

**Comment by Kamuish** [comment]
@dfm I have been looking further into your code and noticed that changing the parameter_bounds is not trivial, since the property @parameter_bounds has the same name as the class attribute, thus leading to an infinite cycle.   Was this made by a design decision to not allow changing the bounds after the kernel is created or was it some unpredicted consequence ?

**Pull request closed without merging**
